version: "3.9"
services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3306:3306"
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8306:80"
    links:
      - db-mysql:db
    depends_on:
      - db-mysql
  Achat:
    container_name: Achat
    build: ./
    ports:
      - "3089:8089"
    environment:
      #port 8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/achat?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    image: "achat-image"
    restart: unless-stopped