version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  app-achat:
    depends_on:
      - mysql
    image: achat
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/achatdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    stdin_open: true
    tty: true
volumes:
  db: